### ISSUE TITLE
ImportError: cannot import name gen_distribution_ops

### ISSUE THREAD

**Issue by ryanprinster** [deepmind/trfl#9] opened 2019-02-06 19:11 UTC
When I try to import trfl, similarly to [this](https://colab.research.google.com/drive/1yP8E9_CCO4NZ5XMYYrPOqSLfR4LlVeB0#scrollTo=Axy2D-N7InE9) public trfl colab notebook online, I get 

(Note I tried this in both python 2 and 3 notebooks, met with the same results)
```ImportErrorTraceback (most recent call last)
<ipython-input-3-dd69192d7d7c> in <module>()
----> 1 import trfl

/usr/local/lib/python2.7/dist-packages/trfl/__init__.py in <module>()
     29 from trfl.discrete_policy_gradient_ops import discrete_policy_gradient_loss
     30 from trfl.discrete_policy_gradient_ops import sequence_advantage_actor_critic_loss
---> 31 from trfl.dist_value_ops import categorical_dist_double_qlearning
     32 from trfl.dist_value_ops import categorical_dist_qlearning
     33 from trfl.dist_value_ops import categorical_dist_td_learning

/usr/local/lib/python2.7/dist-packages/trfl/dist_value_ops.py in <module>()
     31 import tensorflow as tf
     32 from trfl import base_ops
---> 33 from trfl import distribution_ops
     34 
     35 Extra = collections.namedtuple("dist_value_extra", ["target"])

/usr/local/lib/python2.7/dist-packages/trfl/distribution_ops.py in <module>()
     28 import tensorflow as tf
     29 import tensorflow_probability as tfp
---> 30 from trfl import gen_distribution_ops
     31 
     32 

ImportError: cannot import name gen_distribution_ops
```

(Also, if I install trfl via pip instead of cloning from git, error messages look similar with this added on the end)

```

/usr/local/lib/python2.7/dist-packages/trfl/gen_distribution_ops.py in <module>()
      1 import tensorflow as tf
----> 2 _op_lib = tf.load_op_library(tf.resource_loader.get_path_to_datafile("_gen_distribution_ops.so"))
      3 project_distribution = _op_lib.project_distribution
      4 del _op_lib, tf

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.pyc in load_op_library(library_filename)
     59     RuntimeError: when unable to load the library or get the python wrappers.
     60   """
---> 61   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     62 
     63   op_list_str = py_tf.TF_GetOpList(lib_handle)
```

**Comment by superbobry** [comment] 2019-02-08 20:20
Hi @ryanprinster, 

It seems Python fails to load a native library with custom TensorFlow ops which is part of `trfl`. Could you please attach 

* the full stacktrace you get when importing `trfl`, and
* the output of `pip show -f trfl`

so we could diagnose the cause of that?

**Comment by ryanprinster** [comment] 2019-02-08 20:31
Running in python 2 colab notebooks, `import trfl` gives me the following:

```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.


NotFoundErrorTraceback (most recent call last)
<ipython-input-2-dd69192d7d7c> in <module>()
----> 1 import trfl

/usr/local/lib/python2.7/dist-packages/trfl/__init__.py in <module>()
     29 from trfl.discrete_policy_gradient_ops import discrete_policy_gradient_loss
     30 from trfl.discrete_policy_gradient_ops import sequence_advantage_actor_critic_loss
---> 31 from trfl.dist_value_ops import categorical_dist_double_qlearning
     32 from trfl.dist_value_ops import categorical_dist_qlearning
     33 from trfl.dist_value_ops import categorical_dist_td_learning

/usr/local/lib/python2.7/dist-packages/trfl/dist_value_ops.py in <module>()
     31 import tensorflow as tf
     32 from trfl import base_ops
---> 33 from trfl import distribution_ops
     34 
     35 Extra = collections.namedtuple("dist_value_extra", ["target"])

/usr/local/lib/python2.7/dist-packages/trfl/distribution_ops.py in <module>()
     28 import tensorflow as tf
     29 import tensorflow_probability as tfp
---> 30 from trfl import gen_distribution_ops
     31 
     32 

/usr/local/lib/python2.7/dist-packages/trfl/gen_distribution_ops.py in <module>()
      1 import tensorflow as tf
----> 2 _op_lib = tf.load_op_library(tf.resource_loader.get_path_to_datafile("_gen_distribution_ops.so"))
      3 project_distribution = _op_lib.project_distribution
      4 del _op_lib, tf

/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.pyc in load_op_library(library_filename)
     59     RuntimeError: when unable to load the library or get the python wrappers.
     60   """
---> 61   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     62 
     63   op_list_str = py_tf.TF_GetOpList(lib_handle)

NotFoundError: /usr/local/lib/python2.7/dist-packages/trfl/_gen_distribution_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewEPFPNS_8OpKernelEPNS_20OpKernelConstructionEE
```

If instead I do `import tensorflow as tf` beforehand, I get the following

```
ImportErrorTraceback (most recent call last)
<ipython-input-4-dd69192d7d7c> in <module>()
----> 1 import trfl

/usr/local/lib/python2.7/dist-packages/trfl/__init__.py in <module>()
     29 from trfl.discrete_policy_gradient_ops import discrete_policy_gradient_loss
     30 from trfl.discrete_policy_gradient_ops import sequence_advantage_actor_critic_loss
---> 31 from trfl.dist_value_ops import categorical_dist_double_qlearning
     32 from trfl.dist_value_ops import categorical_dist_qlearning
     33 from trfl.dist_value_ops import categorical_dist_td_learning

/usr/local/lib/python2.7/dist-packages/trfl/dist_value_ops.py in <module>()
     30 # Dependency imports
     31 import tensorflow as tf
---> 32 from trfl import base_ops
     33 from trfl import distribution_ops
     34 

ImportError: cannot import name base_ops
```

`pip show -f trfl` gives

```
Name: trfl
Version: 1.0
Summary: trfl is a library of building blocks for reinforcement learning algorithms.
Home-page: http://www.github.com/deepmind/trfl/
Author: DeepMind
Author-email: trfl-steering@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, numpy, dm-sonnet, absl-py
Required-by: 
Files:
  trfl-1.0.dist-info/INSTALLER
  trfl-1.0.dist-info/LICENSE
  trfl-1.0.dist-info/METADATA
  trfl-1.0.dist-info/RECORD
  trfl-1.0.dist-info/WHEEL
  trfl-1.0.dist-info/top_level.txt
  trfl/__init__.py
  trfl/__init__.pyc
  trfl/_gen_distribution_ops.so
  trfl/action_value_ops.py
  trfl/action_value_ops.pyc
  trfl/base_ops.py
  trfl/base_ops.pyc
  trfl/clipping_ops.py
  trfl/clipping_ops.pyc
  trfl/discrete_policy_gradient_ops.py
  trfl/discrete_policy_gradient_ops.pyc
  trfl/dist_value_ops.py
  trfl/dist_value_ops.pyc
  trfl/distribution_ops.py
  trfl/distribution_ops.pyc
  trfl/dpg_ops.py
  trfl/dpg_ops.pyc
  trfl/gen_distribution_ops.py
  trfl/gen_distribution_ops.pyc
  trfl/indexing_ops.py
  trfl/indexing_ops.pyc
  trfl/periodic_ops.py
  trfl/periodic_ops.pyc
  trfl/pixel_control_ops.py
  trfl/pixel_control_ops.pyc
  trfl/policy_gradient_ops.py
  trfl/policy_gradient_ops.pyc
  trfl/retrace_ops.py
  trfl/retrace_ops.pyc
  trfl/sequence_ops.py
  trfl/sequence_ops.pyc
  trfl/target_update_ops.py
  trfl/target_update_ops.pyc
  trfl/value_ops.py
  trfl/value_ops.pyc
  trfl/vtrace_ops.py
  trfl/vtrace_ops.pyc
```

My apologies if this is not a trfl issue.

**Comment by superbobry** [comment] 2019-02-11 14:30
I think the failure is caused by an older version of TensorFlow (1.4). Could you try installing 1.12 and let us know if that works?

**Comment by ryanprinster** [comment] 2019-02-11 16:06
This seems to work in python 2 notebooks, which works for me.

(Note that I still get the same error in python 3 notebooks, but still not essential for me right now).

**Comment by superbobry** [comment] 2019-02-11 20:51
In theory, there should be nothing Python 2/3-specific causing that, i.e. reinstalling TensorFlow for Python 3.X should have the same effect. 

You can always check the TensorFlow version via

```python
>>> import tensorflow as tf
>>> tf.__version__
'1.12.0'
```

**Comment by Kissy** [comment] 2019-02-11 22:18
The issue only appears with TF 1.13-RC1. 
It seems that Google Colab now provides this version by default.

**Comment by diegolascasas** [comment] 2019-02-12 15:11
Unfortunately there is an incompatibility between custom ops compiled for version 1.12 and 1.13-RC1.
We officially support Tensorflow's latest release, which is 1.12. We're working out if there is any way of getting around this in Google Colab, but for now you can use Tensorflow 1.12 by running
`!pip install tensorflow==1.12` before loading it in Colab.

**Comment by CWBlumey** [comment] 2019-02-24 21:23
I have tensorflow 1.12.0, but I also experience the same issues when attempting to import trfl - unable to import gen_distribution_ops. Doing a quick search through trfl, it appears that there are no references to `gen_distribution_ops` being defined, although it is imported in `distribution_ops`. 

I installed via `pip install git+git://github.com/deepmind/trfl.git`

**Comment by AurelianTactics** [comment] 2019-02-24 21:46
> I have tensorflow 1.12.0, but I also experience the same issues when attempting to import trfl - unable to import gen_distribution_ops. Doing a quick search through trfl, it appears that there are no references to `gen_distribution_ops` being defined, although it is imported in `distribution_ops`.
> 
> I installed via `pip install git+git://github.com/deepmind/trfl.git`. Perhaps there is a file missing?

I wrote the colab file linked in the initial issue post. To get trfl working with colab again I did the following:

First cell:
```
!pip install tensorflow==1.12

import os
os.kill(os.getpid(), 9)
```
Next cell:
`!pip install trfl`

The old way of pip installing with git no longer worked for me (!pip install git+git://github.com/deepmind/trfl.git), even when using tf 1.12.

**Comment by CWBlumey** [comment] 2019-02-24 22:06
Thanks for the colab solution (I confirmed, it does work for colab), but I was hoping to install TRFL on my home computer. `pip install tensorflow==1.12` doesn't find any matching repositories (it only sees 1.13), so the method doesn't appear to work in my environment (Ubuntu 18.04 LTS fresh install)

**Comment by AurelianTactics** [comment] 2019-02-24 22:21
> Thanks for the colab solution (I confirmed, it does work for colab), but I was hoping to install TRFL on my home computer. `pip install tensorflow==1.12` doesn't find any matching repositories (it only sees 1.13), so the method doesn't appear to work in my environment (Ubuntu 18.04 LTS fresh install).
> 
> For what it's worth, I'm running python 3.6.0

I was also able to run in on Ubuntu 16.04. I installed it through an Anaconda env. Not sure why tensorflow wouldn't pip install for you. For those checking here and having issues with install, these steps worked for me:

Install Anaconda on Linux: https://docs.anaconda.com/anaconda/install/
Create a new environment:
`conda create -n myenv python=3.6`
Activate the environment:
`source activate myenv`
Install Tensorflow:
`pip install tensorflow==1.12 #pip install tensorflow-gpu==1.12`
Install TRFL and other packages:
`pip install trfl tensorflow-probability wrapt`

**Comment by superbobry** [comment] 2019-02-25 16:21
> pip install git+git://github.com/deepmind/trfl.git

@CWBlumey yes, this way of installing TRFL no longer works, because currently we compile TF custom ops via Blaze avoiding distutils/setuptools. The easiest (and recommended) way of installing TRFL is by downloading one of the prebuilt wheels from PyPI. `pip` will do that automatically on `pip install trfl`.

**Comment by akanksha95** [comment] 2019-03-12 22:55
I installed trfl from source (with changes from pull request #12) on MacOS and am getting a similar error with importing gen_distribution_ops. Specifically, I see the following error:

```
.
.
.
from trfl import gen_distribution_ops
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trfl/gen_distribution_ops.py", line 2, in <module>
    _op_lib = tf.load_op_library(tf.resource_loader.get_path_to_datafile("_gen_distribution_ops.so"))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trfl/_gen_distribution_ops.so, 6): Symbol not found: __ZN10tensorflow12OpDefBuilder3DocENS_11StringPieceE
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trfl/_gen_distribution_ops.so
  Expected in: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/../libtensorflow_framework.so
 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/trfl/_gen_distribution_ops.so
```

I tried both 1.12.0 and 1.13.1 versions of tensorflow and got the same error. Does anyone using MacOS see the same issue?

**Comment by abdel** [comment] 2019-03-13 00:42
@akanksha95 It seems like `gen_distribution_ops` is there, but there's a missing symbol in the built library its loading, so likely something went wrong in the build?

I'm currently able to build and run TRFL on macOS as per #12 with the following environment:
- TensorFlow (CPU) 1.12.0
- macOS 10.14.3
- Bazel 0.23.1

I would suggest clearing out your Bazel cache (usually in `/private/var/tmp/_bazel_USERNAME`) and try re-building again, and see how that goes.

**Comment by akanksha95** [comment] 2019-03-13 16:05
@abdel that didn't help, still getting the same error. I do have the same environment as you. I am wondering if it has anything to do with multiple python versions. Looking into it.

**Comment by mtthss** [comment] 2019-03-14 16:34
@akanksha95, @abdel,

we now have pre-built binaries for both MacOS and Ubuntu
you can install them with `pip install trfl`

- Ubuntu: make sure you have TensorFlow 1.12.0 and TensorFlow Probability 0.5
- MacOS: make sure you have TensorFlow 1.13.1 and TensorFlow Probability 0.6

**Comment by abdel** [comment] 2019-03-17 23:20
@mtthss The `gen_distribution_ops.so` seems to be missing when installing in a fresh environment with TF 13.1 and TF-Probability 0.6 on macOS.

```
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import trfl

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages/trfl/__init__.py", line 31, in <module>
    from trfl.dist_value_ops import categorical_dist_double_qlearning
  File "/Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages/trfl/dist_value_ops.py", line 33, in <module>
    from trfl import distribution_ops
  File "/Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages/trfl/distribution_ops.py", line 30, in <module>
    from trfl import gen_distribution_ops
  File "/Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages/trfl/gen_distribution_ops.py", line 2, in <module>
    _op_lib = tf.load_op_library(tf.resource_loader.get_path_to_datafile("_gen_distribution_ops.so"))
  File "/Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages/trfl/_gen_distribution_ops.so, 6): image not found
```

```
Name: trfl
Version: 1.0
Summary: trfl is a library of building blocks for reinforcement learning algorithms.
Home-page: http://www.github.com/deepmind/trfl/
Author: DeepMind
Author-email: trfl-steering@google.com
License: Apache 2.0
Location: /Users/Abdel/Developer/anaconda/envs/tf2/lib/python3.6/site-packages
Requires: numpy, six, dm-sonnet, absl-py, wrapt
Required-by:
Files:
  trfl-1.0.dist-info/INSTALLER
  trfl-1.0.dist-info/LICENSE
  trfl-1.0.dist-info/METADATA
  trfl-1.0.dist-info/RECORD
  trfl-1.0.dist-info/WHEEL
  trfl-1.0.dist-info/top_level.txt
  trfl/__init__.py
  trfl/__pycache__/__init__.cpython-36.pyc
  trfl/__pycache__/action_value_ops.cpython-36.pyc
  trfl/__pycache__/base_ops.cpython-36.pyc
  trfl/__pycache__/clipping_ops.cpython-36.pyc
  trfl/__pycache__/discrete_policy_gradient_ops.cpython-36.pyc
  trfl/__pycache__/dist_value_ops.cpython-36.pyc
  trfl/__pycache__/distribution_ops.cpython-36.pyc
  trfl/__pycache__/dpg_ops.cpython-36.pyc
  trfl/__pycache__/gen_distribution_ops.cpython-36.pyc
  trfl/__pycache__/indexing_ops.cpython-36.pyc
  trfl/__pycache__/periodic_ops.cpython-36.pyc
  trfl/__pycache__/pixel_control_ops.cpython-36.pyc
  trfl/__pycache__/policy_gradient_ops.cpython-36.pyc
  trfl/__pycache__/retrace_ops.cpython-36.pyc
  trfl/__pycache__/sequence_ops.cpython-36.pyc
  trfl/__pycache__/target_update_ops.cpython-36.pyc
  trfl/__pycache__/value_ops.cpython-36.pyc
  trfl/__pycache__/vtrace_ops.cpython-36.pyc
  trfl/action_value_ops.py
  trfl/base_ops.py
  trfl/clipping_ops.py
  trfl/discrete_policy_gradient_ops.py
  trfl/dist_value_ops.py
  trfl/distribution_ops.py
  trfl/dpg_ops.py
  trfl/gen_distribution_ops.py
  trfl/indexing_ops.py
  trfl/periodic_ops.py
  trfl/pixel_control_ops.py
  trfl/policy_gradient_ops.py
  trfl/retrace_ops.py
  trfl/sequence_ops.py
  trfl/target_update_ops.py
  trfl/value_ops.py
  trfl/vtrace_ops.py
```

**Comment by abdel** [comment] 2019-03-17 23:30
Works okay when building from source.

My wheel: `trfl-1.0-cp36-cp36m-macosx_10_7_x86_64.whl`
Your wheel: `trfl-1.0-cp36-cp36m-macosx_10_6_intel.whl` (when using `pip install`)

**Comment by mtthss** [comment] 2019-03-18 09:03
Lets consolidate the two issues. I am closing this one, and let's continue the discussion on #10.

**Closed by mtthss** 2019-03-18 09:03 UTC
